apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgis-data-disk
  labels:
    name: pgis-data-disk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "pgis-data-disk"
    fsType: "ext4"
